### ISSUE TITLE
Add test suites

### ISSUE THREAD

**Issue by ecxyzzy** [icssc/peterportal-api-next#80]
Everyone's favorite part of software development :upside_down_face: 

## Tasks
- Unit testing
  - [ ] Create `apps/api/tests/unit` which will host all unit tests
- Specification testing
  - [ ] Create `tests/api/spec` which will host all specification tests
  - [ ] Run tests by `fetch`ing endpoint given in an environment variable (defaults to `localhost:8080` if not present)
- GitHub Actions integrations
  - [ ] Run unit tests before deploy
  - [ ] Report unit testing coverage in PR
  - [ ] Run specification tests on staging instance after deploy

**Comment by ecxyzzy** [comment]
Will do at some point I promise
